---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(readxl)
library(janitor)
library(ggplot2)
library(plotly)
library(forcats)
library(gt)
```

```{r, read in data}

data <-read_excel("Track two dialogue database.xlsx") %>% 
  
  # read in data 
  
  clean_names() %>% 
  
  # clean it up-- some column titles imported wierdly from the excel file 
  
  mutate("length" = end_date - start_date + 1) %>%
  
  # add lenght column for stacking purposes
  
  mutate("Dialogue" = dialogues) %>% 

  # use mutate to capitalize dialogues, this will make the hovertext look nicer 
  
  mutate("start_date2" = start_date) %>% 
  mutate("end_date2" = end_date) %>%

  # duplicate start and end dates so that I can have this information both as separate columns and
  # within one column 
  
  pivot_longer(start_date2:end_date2, names_to = "start_or_end", values_to = "year") %>% 
  
  # do the pivot to get start and end in one column named length 
  
  mutate("short_name" = fct_reorder(short_name, length))

  # reorder data by length so that chart will factor nicely below 
  

```

```{r, make graph, warning= FALSE}

plot <- ggplot(data) +
  
  # make a ggplot 
  
  geom_segment(aes(
    y = short_name, 
    yend = short_name, 
    x = start_date, 
    xend = end_date, 
    color = strong_focus_on_arms_control, 
    text = paste0(short_name))
    )+
  
  # use geom_segement to make lines, could also use geom_line here
  
  geom_point(aes(
    y = short_name, 
    x = year, 
    color = strong_focus_on_arms_control, 
    text = paste0(short_name))
    )+
  
  # add geom_point layer to enphasize start and end of dialogues  
  
  geom_vline(xintercept = 1991, linetype = "dotted")+
  
  # add line to show New START negotiation
  
  scale_x_continuous(breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  
  # add breaks so that every 10 years are marked da
  
  scale_color_manual(values = c("Yes" = "dodgerblue2", "No" = "darkorange2"))+
  
  # set colors
  
  theme_minimal()+
  
  # set theme 
  
  theme(axis.title.y = element_blank(), axis.text.y = element_blank())+
  
  # take out very long x axis labels 

  labs(title = "Selected U.S. Russia Track Two Enagements, 1957-2020", 
       x = "Year", 
       color = "Exclusive focus on arms control?")+
  
  # add title and x-axis label 
  
  theme(legend.position= c(0.2, 0.2), legend.background = element_rect(fill = "white"))+ 
  
  # edit location and look of key 
  
  theme(plot.title = element_text(hjust = 0.5))
  
  # center title 


ggsave("plot.png", plot = plot, height = 10, width = 20, units = "cm")

ggplotly(p = plot, tooltip = "text") %>%
  
  # plotly it, mostly for the hovertext option. Use tooltip so that hovertext shows 
  # the name of the dialogue 
layout(
    legend = list(
      x = 0.05, 
      y = 0.1, 
      title = list(text = "Exclusive focus on arms control?"), 
      borderwidth = 1)
  )


# add legend to plotly 

```

```{r, make graph, warning = FALSE}

data2 <- data %>% mutate(start_date = case_when(start_date >=1991 ~ start_date,
                                         TRUE ~ 1991))

plot2 <- ggplot(data2) +
  
  # make a ggplot 
  
  geom_segment(aes(
    y = short_name, 
    yend = short_name, 
    x = start_date, 
    xend = end_date, 
    color = strong_focus_on_arms_control, 
    text = paste0(short_name))
    )+
  
  # use geom_segement to make lines, could also use geom_line here
  
  geom_point(aes(
    y = short_name, 
    x = year, 
    color = strong_focus_on_arms_control, 
    text = paste0(short_name))
    )+
  
  # add geom_point layer to enphasize start and end of dialogues  
  
  geom_vline(xintercept = 2009, linetype = "dashed")+
  
  geom_text(aes(x = 2009.5, label = "New START"), y = 5.3, angle = -90)+
  
  # add line to show New START negotiation
  
  geom_vline(xintercept = 2002, linetype = "dashed")+
  
  geom_text(aes(x = 2002.5, label = "SORT"), y = 3.6, angle = -90)+
  
  # add line to show SORT negotiaiton 
  
  scale_x_continuous(breaks = c(1991, 2000, 2010, 2020), limits = c(1991,2020))+
  
  # add breaks so that every 10 years are marked da
  
  scale_color_manual(values = c("Yes" = "dodgerblue2", "No" = "darkorange2"))+
  
  # set colors
  
  theme_minimal()+
  
  # set theme 
  
  theme(axis.title.y = element_blank(), axis.text.y = element_blank())+
  
  # take out very long x axis labels 

  labs(title = "U.S.-Russia Track Two Enagements, 1991-2020", 
       x = "Year", 
       color = "Exclusive focus
  on arms control?")+
  
  # add title and x-axis label 
  
  theme(legend.background = element_rect(fill = "white"))+ 
  
  # edit location and look of key 
  
  theme(plot.title = element_text(hjust = 0.5)) +
  
  theme(legend.position= c(0.2, 0.2), legend.background = element_rect(fill = "white"))
  
  # center title 
```

```{r, save image and ggplot it, warning = FALSE}

ggsave("plot2.png", plot = plot2, height = 10, width = 20, units = "cm")

ggplotly(p = plot2, tooltip = "text") %>%
  
  # plotly it, mostly for the hovertext option. Use tooltip so that hovertext shows 
  # the name of the dialogue 
layout(
    legend = list(
      x = 0.05, 
      y = 0.1, 
      title = list(text = "Exclusive focus on arms control?"), 
      borderwidth = 1)
  )


# add legend to plotly 


```

```{r, table}

data3 <- data %>% 
  filter(short_name %in% c("Pugwash","Dartmouth Conference","NAS CISAC", "IPPNW", "Institue on East-West Studies", "IREX", "PONARS", "MIT Science, Tech & Global Security Working Group","Luxembourg Forum", "Ivanov-Talbott-Albright Dialogue", "NDU dialogue", "Nixon center project", "CEIP working group on U.S.-Russia relations")) %>% 
  group_by(dialogues, start_date, end_date) %>% 
  count(dialogues) %>% 
  select(dialogues:end_date) %>% 
  ungroup()

data3 %>% 
  gt() %>% 
  tab_header(
    title = "Track Two Dialogues ongoing during New START negotiations"
  ) %>%
  
# Added titles. I found  information on how to use gt at the bottom of the github gt page. 
  
  cols_label(
    dialogues = "Name",
    start_date = "First Meeting",
    end_date = "Latest Meeting"
  )


```

